# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config/game_offsets.example.json', 'config'),
        ('config/gamedata.example.json', 'config'),
        ('config/champions.json', 'config'),
        ('config/patron_roster.json', 'config'),
        ('config/ultimate_attacks.json', 'config'),
        ('config/specializations.json', 'config'),
        ('documentation', 'documentation'),
    ],
    hiddenimports=[
        'build_info',
        'ic_gamedata',
        'ic_gamedata.paths',
        'ic_gamedata.log_parser',
        'ic_gamedata.stats',
        'ic_gamedata.credentials',
        'ic_gamedata.api_client',
        'ic_gamedata.party_advisor',
        'ic_gamedata.party_advisor_specializations',
        'ic_gamedata.adventure_restrictions',
        'ic_gamedata.patron_roster',
        'ic_gamedata.formation_advisor',
        'ic_gamedata.formation_advisor.loader',
        'ic_gamedata.formation_advisor.evaluator',
        'ic_gamedata.seat_advisor',
        'ic_gamedata.seat_advisor.report_builder',
        'ic_automation',
        'ic_automation.controller',
        'ic_automation.worker',
        'ic_automation.settings',
        'ic_automation.win_input',
        'ic_ui',
        'ic_ui.pyside_app',
        'ic_gamedata.specializations',
        'ic_gamedata.specialization_rules',
        'ic_gamedata.specialization_rules.loader',
        'ic_gamedata.specialization_rules.evaluator',
        'ic_reader',
        'ic_reader.resolver',
        'ic_reader.config_loader',
        'ic_reader.memory',
        'ic_reader.process',
        'ic_reader.pointers',
        'ic_reader.models',
        'ic_reader.validators',
        'psutil',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='IdleChampionsApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
